Repository getappmap/appmap-js, pull requests merged in 2023-10, with the labels that each got.

#1362 feat: Disable diagram tabs in 'diff' mode
  packages/components/src/components/DetailsButton.vue
  packages/components/src/components/DetailsPanelEvent.vue
  packages/components/src/components/TabButton.vue
  packages/components/tests/e2e/specs/appmap/sequenceDiagramDiff.spec.js
Labels: well-defined

#1440 feat: Suppress report sections
  packages/cli/resources/change-report/changed-appmaps/heading.hbs
  packages/cli/resources/change-report/failed-tests/heading.hbs
  packages/cli/resources/change-report/findings/details.hbs
  packages/cli/resources/change-report/findings/heading.hbs
  packages/cli/resources/change-report/new-appmaps/heading.hbs
  packages/cli/resources/change-report/openapi-diff/heading.hbs
  packages/cli/resources/change-report/removed-appmaps/heading.hbs
  packages/cli/src/cmds/compare-report/ChangeReport.ts
  packages/cli/src/cmds/compare-report/MarkdownReport.ts
  packages/cli/src/cmds/compare-report/Preprocessor.ts
  packages/cli/src/cmds/compare-report/ReportSection.ts
  packages/cli/src/cmds/compare-report/helpers.ts
  packages/cli/tests/unit/compareReport/changedAppMaps.spec.ts
  packages/cli/tests/unit/compareReport/expectedReport.md.txt
  packages/cli/tests/unit/compareReport/failedTests.spec.ts
  packages/cli/tests/unit/compareReport/findings.spec.ts
  packages/cli/tests/unit/compareReport/newAppMaps.spec.ts
  packages/cli/tests/unit/compareReport/openapiDiff.spec.ts
Labels: enhancement

#1425 feat: Report SQL changes (experimental section)
  packages/cli/package.json
  packages/cli/resources/change-report/changed-appmaps/details.hbs
  packages/cli/resources/change-report/failed-tests/details.hbs
  packages/cli/resources/change-report/findings/details.hbs
  packages/cli/resources/change-report/new-appmaps/details.hbs
  packages/cli/resources/change-report/openapi-diff/details.hbs
  packages/cli/resources/change-report/removed-appmaps/details.hbs
  packages/cli/resources/change-report/sql-diff/details.hbs
  packages/cli/resources/change-report/sql-diff/heading.hbs
  packages/cli/src/cmds/archive/archive.ts
  packages/cli/src/cmds/archive/unpackArchive.ts
  packages/cli/src/cmds/compare-report/ChangeReport.ts
  packages/cli/src/cmds/compare-report/MarkdownReport.ts
  packages/cli/src/cmds/compare-report/Preprocessor.ts
  packages/cli/src/cmds/compare-report/ReportSection.ts
  packages/cli/src/cmds/compare-report/formatAPILocation.ts
  packages/cli/src/cmds/compare-report/helpers.ts
  packages/cli/src/cmds/compare/ChangeReport.ts
  packages/cli/src/cmds/compare/ChangeReporter.ts
  packages/cli/src/cmds/compare/ReportFieldCalculator.ts
  packages/cli/src/cmds/compare/SourceDiff.ts
  packages/cli/src/cmds/compare/buildFailure.ts
  packages/cli/src/cmds/compare/compare.ts
  packages/cli/src/cmds/compare/deleteUnreferencedAppMaps.ts
  packages/cli/src/cmds/compare/prepareOutputDir.ts
  packages/cli/src/cmds/compare/reportChanges.ts
  packages/cli/src/diffArchive/ChangeAnalysis.ts
  packages/cli/src/diffArchive/Digests.ts
  packages/cli/src/diffArchive/Paths.ts
  packages/cli/src/diffArchive/RevisionName.ts
  packages/cli/src/diffArchive/SequenceDiagramDigest.ts
  packages/cli/src/diffArchive/SourceDiff.ts
  packages/cli/src/diffArchive/loadFindings.ts
  packages/cli/src/lib/ArchiveMetadata.ts
  packages/cli/src/lib/normalizeAppMapId.ts
  packages/cli/src/lib/resolvePath.ts
  packages/cli/tests/unit/compare/ChangeReporter.spec.ts
  packages/cli/tests/unit/compare/ReportFieldCalculator.spec.ts
  packages/cli/tests/unit/compare/compare.spec.ts
  packages/cli/tests/unit/compareReport/changedAppMaps.spec.ts
  packages/cli/tests/unit/compareReport/expectedReport.md.txt
  packages/cli/tests/unit/compareReport/failedTests.spec.ts
  packages/cli/tests/unit/compareReport/findings.spec.ts
  packages/cli/tests/unit/compareReport/formatAPILocation.spec.ts
  packages/cli/tests/unit/compareReport/newAppMaps.spec.ts
  packages/cli/tests/unit/compareReport/openapiDiff.spec.ts
  packages/cli/tests/unit/compareReport/removedAppMaps.spec.ts
  packages/cli/tests/unit/diffArchive/ChangeAnalysis.spec.ts
  packages/cli/tests/unit/diffArchive/SourceDiff.spec.ts
  packages/cli/tests/unit/diffArchive/fixtureData/addDeleteChangeRemoveDiff.txt
  packages/cli/tests/unit/diffArchive/fixtureData/exampleDiff.txt
  packages/cli/tests/unit/diffArchive/fixtureData/expectedDiff.txt
  packages/cli/tests/unit/diffArchive/fixtureData/parsedUnifiedDiff.json
  packages/cli/tests/unit/diffArchive/isChanged.spec.ts
  packages/cli/tests/unit/diffArchive/isNew.spec.ts
  packages/cli/tests/unit/fixtures/compare/.appmap/change-report/all-succeeded/change-report.json
  yarn.lock
Labels: enhancement

#1449 Change mentions of "Runnable recording" to "code block recording" in install instructions
  packages/components/src/components/install-guide/record-instructions/IntelliJ.vue
  packages/components/src/components/install-guide/record-instructions/Java.vue
Labels: bug

#1448 feat: Summary report
  packages/cli/resources/change-report/findings/details.hbs
  packages/cli/resources/change-report/findings/inline/finding.hbs
  packages/cli/resources/inlines/stack.hbs
  packages/cli/resources/inventory-report/summary/summary.hbs
  packages/cli/src/cmds/compare-report/ChangeReport.ts
  packages/cli/src/cmds/compare-report/MarkdownReport.ts
  packages/cli/src/cmds/compare-report/ReportSection.ts
  packages/cli/src/cmds/compare/reportChanges.ts
  packages/cli/src/cmds/inventory-report/MarkdownReport.ts
  packages/cli/src/cmds/inventory-report/Reporter.ts
  packages/cli/src/cmds/inventory-report/SummaryReporter.ts
  packages/cli/src/cmds/inventory-report/WelcomeReporter.ts
  packages/cli/src/cmds/inventory-report/inventoryReport.ts
  packages/cli/src/cmds/inventory/Report.ts
  packages/cli/src/cmds/inventory/analyzers/collectFindings.ts
  packages/cli/src/cmds/inventory/analyzers/collectHTTPClientRequests.ts
  packages/cli/src/cmds/inventory/analyzers/collectHTTPServerRequests.ts
  packages/cli/src/cmds/inventory/analyzers/collectLabels.ts
  packages/cli/src/cmds/inventory/analyzers/collectMetadata.ts
  packages/cli/src/cmds/inventory/analyzers/collectPackageDependencies.ts
  packages/cli/src/cmds/inventory/analyzers/collectRoutes.ts
  packages/cli/src/cmds/inventory/analyzers/collectSQLQueries.ts
  packages/cli/src/cmds/inventory/analyzers/collectSQLTables.ts
  packages/cli/src/cmds/inventory/buildReport.ts
  packages/cli/src/cmds/inventory/inventory.ts
  packages/cli/src/cmds/inventory/readIndexFile.ts
  packages/cli/src/diffArchive/ChangeAnalysis.ts
  packages/cli/src/lib/loadAppMapConfig.ts
  packages/cli/src/report/ReportTemplate.ts
  packages/cli/src/report/helpers.ts
  packages/cli/src/report/loadReportTemplate.ts
  packages/cli/src/report/urlHelpers.ts
  packages/cli/tests/unit/compareReport/changedAppMaps.spec.ts
  packages/cli/tests/unit/compareReport/expectedReport.md.txt
  packages/cli/tests/unit/compareReport/failedTests.spec.ts
  packages/cli/tests/unit/compareReport/findings.spec.ts
  packages/cli/tests/unit/compareReport/helpers.spec.ts
  packages/cli/tests/unit/compareReport/newAppMaps.spec.ts
  packages/cli/tests/unit/compareReport/openapiDiff.spec.ts
  packages/cli/tests/unit/compareReport/removedAppMaps.spec.ts
  packages/cli/tests/unit/compareReport/testHelper.ts
  packages/cli/tests/unit/compareReport/verifyReportContents.ts
  packages/cli/tests/unit/inventoryReport/inventory.json
  packages/cli/tests/unit/inventoryReport/inventory.summary.spec.ts
  packages/cli/tests/unit/inventoryReport/inventory.welcome.spec.ts
  packages/cli/tests/unit/inventoryReport/summary.md.txt
  packages/cli/tests/unit/inventoryReport/welcome.md.txt
Labels: enhancement
