Repository getappmap/appmap-js, pull requests merged in 2023-09, with the labels that each got.

#1351 feat: Hide SQL SHOW from compare
  packages/cli/src/cmds/archive/buildFilter.ts
  packages/cli/src/lib/loadAppMapConfig.ts
  packages/cli/tests/unit/archive/buildFilter.spec.ts
Labels: enhancement

#1339 feat: Sequence diagram diff in appmap
  packages/components/src/components/DetailsPanelFilters.vue
  packages/components/src/components/DiagramSequence.vue
  packages/components/src/components/sequence/Actor.vue
  packages/components/src/lib/isPrecomputedSequenceDiagram.js
  packages/components/src/pages/VsCodeExtension.vue
  packages/components/src/store/vsCode.js
  packages/components/src/stories/DiagramSequence.stories.js
  packages/components/src/stories/VsCodeExtension.stories.js
  packages/components/src/stories/data/sequence-diff/Users_profile_profile_display.appmap.json
  packages/components/src/stories/data/sequence-diff/Users_profile_profile_display.diff.sequence.json
  packages/components/src/stories/data/sequence/Users_profile_profile_display.diff.sequence.json
  packages/components/src/stories/data/sequence/appland_api_key_diff.sequence.json
  packages/components/tests/e2e/specs/appmap/sequenceDiagramDiff.spec.js
  packages/scanner/package.json
  yarn.lock
Labels: enhancement

#1361 fix: Ignore invalid OpenAPI paths
  packages/cli/src/cmds/openapi/DefinitionGenerator.ts
  packages/openapi/src/model.ts
  packages/openapi/test/model.spec.ts
Labels: bug

#1360 fix: Long call labels are cut off
  packages/components/src/components/sequence/CallLabel.vue
  packages/components/src/stories/VsCodeExtension.stories.js
  packages/components/src/stories/data/long_call_labels_are_cut_off.appmap.json
  packages/components/tests/e2e/specs/appmap/longCallLabelsSequenceDiagram.spec.js
Labels: sequence diagrams

#1395 feat: Update PR change report
  packages/cli/.gitignore
  packages/cli/resources/change-report.hbs
  packages/cli/resources/change-report/changed-appmaps/details.hbs
  packages/cli/resources/change-report/changed-appmaps/heading.hbs
  packages/cli/resources/change-report/failed-tests/details.hbs
  packages/cli/resources/change-report/failed-tests/heading.hbs
  packages/cli/resources/change-report/findings/details.hbs
  packages/cli/resources/change-report/findings/heading.hbs
  packages/cli/resources/change-report/new-appmaps/details.hbs
  packages/cli/resources/change-report/new-appmaps/heading.hbs
  packages/cli/resources/change-report/openapi-diff/details.hbs
  packages/cli/resources/change-report/openapi-diff/heading.hbs
  packages/cli/src/cmds/archive/analyzeTask.ts
  packages/cli/src/cmds/compare-report/ChangeReport.ts
  packages/cli/src/cmds/compare-report/MarkdownReport.ts
  packages/cli/src/cmds/compare-report/Preprocessor.ts
  packages/cli/src/cmds/compare-report/ReportSection.ts
  packages/cli/src/cmds/compare-report/compareReport.ts
  packages/cli/src/cmds/compare/ChangeReport.ts
  packages/cli/src/cmds/compare/ChangeReporter.ts
  packages/cli/src/cmds/compare/loadFindings.ts
  packages/cli/src/lib/findings.ts
  packages/cli/src/lib/processAppMapDir.ts
  packages/cli/tests/unit/compareReport/changedAppMaps.spec.ts
  packages/cli/tests/unit/compareReport/compareReport.spec.ts
  packages/cli/tests/unit/compareReport/expectedReport-changedAppMaps.md.txt
  packages/cli/tests/unit/compareReport/expectedReport-openapiDiff.md.txt
  packages/cli/tests/unit/compareReport/expectedReport.md.txt
  packages/cli/tests/unit/compareReport/failedTests.spec.ts
  packages/cli/tests/unit/compareReport/findings.spec.ts
  packages/cli/tests/unit/compareReport/newAppMaps.spec.ts
  packages/cli/tests/unit/compareReport/openapiDiff.spec.ts
  packages/cli/tests/unit/compareReport/testHelper.ts
  packages/cli/tests/unit/fixtures/compare/.appmap/change-report/testBase-testHead/change-report.json
  packages/models/types/index.d.ts
Labels: enhancement

#1400 feat: Diff once
  packages/cli/package.json
  packages/cli/src/cmds/compare/ChangeReporter.ts
  packages/cli/src/cmds/compare/DiffLoader.ts
  packages/cli/src/lib/executeCommand.ts
  packages/cli/tests/unit/compare/DiffLoader.spec.ts
  packages/cli/tests/unit/compare/fixtureData/addDeleteChangeRemoveDiff.txt
  packages/cli/tests/unit/compare/fixtureData/exampleDiff.txt
  packages/cli/tests/unit/compare/fixtureData/expectedDiff.txt
  packages/cli/tests/unit/compare/fixtureData/parsedUnifiedDiff.json
  yarn.lock
Labels: enhancement
