Repository getappmap/appmap-js, pull requests merged in 2024-01, with the labels that each got.

#1516 fix: Make API key optional for index watch mode
  packages/cli/src/cmds/index/index.ts
Labels: bug

#1514 fix: "New chat" resets thread
  packages/cli/src/rpc/explain/explain.ts
  packages/components/src/components/chat/Chat.vue
  packages/components/src/pages/Chat.vue
  packages/components/src/pages/ChatSearch.vue
  packages/components/src/stories/ChatSearch.stories.js
  packages/components/tests/unit/chat/ChatComponent.spec.js
  packages/components/tests/unit/chat/ChatHelp.spec.js
  packages/components/tests/unit/chat/ChatSearch.spec.js
  packages/rpc/src/explain.ts
Labels: bug

#1515 fix: Authenticate Chat/ChatSearch frontend clients
  packages/client/src/index.ts
  packages/components/src/components/mixins/authenticatedClient.js
  packages/components/src/pages/Chat.vue
  packages/components/src/pages/ChatSearch.vue
  packages/components/tests/unit/chat/authentication.spec.js
Labels: enhancement

#1519 fix: Allow user scroll
  packages/components/src/components/chat/Chat.vue
  packages/components/src/stories/ChatSearch.stories.js
  packages/components/tests/unit/chat/ChatComponent.spec.js
Labels: bug

#1527 fix: ChatSearch fixes
  packages/cli/src/fulltext/FindEvents.ts
  packages/cli/src/rpc/explain/context.ts
  packages/cli/src/rpc/explain/explain.ts
  packages/cli/src/rpc/explain/lookupSourceCode.ts
  packages/cli/tests/integration/fixtures/search/api_key.search.json
  packages/components/src/components/DiagramComponent.vue
  packages/components/src/components/sequence/CallLabel.vue
  packages/components/src/lib/AppMapRPC.ts
  packages/components/src/pages/ChatSearch.vue
  packages/components/src/pages/VsCodeExtension.vue
  packages/components/src/store/vsCode.js
  packages/components/src/stories/VsCodeExtension.stories.js
  packages/components/tests/unit/chat/AppMapRPC.spec.js
  packages/components/tests/unit/chat/ChatSearch.spec.js
  yarn.lock
Labels: bug

#1528 feat: Apply saved filters
  packages/components/src/assets/compass-icon.svg
  packages/components/src/components/FilterMenu.vue
  packages/components/src/components/chat/Chat.vue
  packages/components/src/components/chat/ChatInput.vue
  packages/components/src/components/chat/UserMessage.vue
  packages/components/src/pages/ChatSearch.vue
  packages/components/src/pages/VsCodeExtension.vue
  packages/components/src/stories/ChatSearch.stories.js
  packages/components/tests/e2e/specs/appmap/share.spec.js
  packages/components/tests/e2e/specs/appmap/statsPanel.spec.js
  packages/components/tests/e2e/specs/appmap/viewFilter.spec.js
  packages/components/tests/unit/filterMenu.spec.js
Labels: enhancement

#1531 feat: Drop Diagnostics info from ChatSearch
  packages/components/src/pages/ChatSearch.vue
Labels: enhancement

#1536 ci: Run appmap-analysis on packages/cli
  .github/workflows/main.yml
Labels: enhancement

#1551 feat: appmap.stats RPC
  appmap.yml
  packages/cli/appmap.yml
  packages/cli/src/cmds/index/index.ts
  packages/cli/src/rpc/appmap/filter.ts
  packages/cli/src/rpc/appmap/stats.ts
  packages/cli/tests/integration/buildRPC.ts
  packages/cli/tests/integration/rpc.appmap.spec.ts
  packages/rpc/src/appmap.ts
Labels: enhancement, navie

#1532 feat: Export AppMap data as JSON
  packages/components/src/components/ExportJSON.vue
  packages/components/src/components/PopperMenu.vue
  packages/components/src/components/sequence/DownloadSequenceDiagram.vue
  packages/components/src/pages/VsCodeExtension.vue
  packages/components/src/stories/VsCodeExtension.stories.js
  packages/components/tests/e2e/specs/appmap/export.spec.js
  packages/components/tests/e2e/specs/appmap/sequenceDiagram.spec.js
  packages/components/tests/e2e/specs/appmap/viewFilter.spec.js
  packages/components/tests/e2e/specs/chat/chatSearch.spec.js
  packages/components/tests/unit/ExportJSON.spec.js
  packages/components/tests/unit/VsCodeExtension.spec.js
Labels: enhancement
