Repository getappmap/appmap-js, pull requests merged in 2024-10, with the labels that each got.

#2021 feat: Ignore .appmap and .navie directories when selecting context
  packages/cli/src/rpc/explain/collectContext.ts
  packages/cli/tests/unit/rpc/explain/pattern.spec.ts
Labels: enhancement

#2020 feat: Report subscription status on thread creation
  packages/cli/tests/integration/rpc.explain.spec.ts
  packages/cli/tests/unit/rpc/explain/Explain.spec.ts
  packages/client/src/ai.ts
Labels: enhancement

#2045 feat: Ignore large data files
  packages/cli/src/fulltext/FileIndex.ts
  packages/cli/tests/unit/fulltext/FileIndex.spec.ts
  packages/cli/tests/unit/rpc/explain/pattern.spec.ts
Labels: enhancement

#2051 fix: mjs file is not binary data
  packages/cli/src/fulltext/FileIndex.ts
  packages/cli/tests/unit/fulltext/FileIndex.spec.ts
Labels: bug

#2046 feat: Ignore more directories of vendored code
  packages/cli/src/rpc/explain/collectContext.ts
  packages/cli/tests/unit/rpc/explain/pattern.spec.ts
Labels: enhancement

#2068 feat: Report AppMap usage stats
  .appmapignore
  packages/cli/src/cmds/archive/index.ts
  packages/cli/src/fingerprint/fingerprintDirectoryCommand.ts
  packages/cli/src/fingerprint/fingerprintWatchCommand.ts
  packages/cli/src/lib/emitUsage.ts
  packages/cli/tests/unit/lib/emitUsage.spec.ts
  packages/client/src/usage.ts
Labels: enhancement

#2069 fix: Fix Usage reporting test
  packages/client/test/usage.spec.ts
Labels: bug

#2050 fix: add locations to explain requests
  .github/actions/setup-node/action.yml
  packages/cli/src/rpc/explain/explain.ts
  packages/cli/src/rpc/explain/navie/history.ts
  packages/cli/src/rpc/explain/navie/ihistory.ts
  packages/cli/src/rpc/explain/navie/inavie.ts
  packages/components/src/components/chat/MarkdownCodeSnippet.vue
  packages/components/src/components/chat/PinEvent.ts
  packages/components/src/lib/AppMapRPC.ts
  packages/components/src/pages/ChatSearch.vue
  packages/navie/src/agent.ts
  packages/navie/src/commands/explain-command.ts
  packages/navie/src/commands/update-command.ts
  packages/navie/src/context.ts
  packages/navie/src/index.ts
  packages/navie/src/navie.ts
  packages/navie/src/services/code-selection-service.ts
  packages/navie/src/services/context-service.ts
  packages/navie/src/services/file-change-extractor-service.ts
  packages/navie/src/user-context.ts
  packages/rpc/src/explain.ts
Labels: build native
